---
cert:
  dir: "/etc/certificates"
  kubelet:
    cert: "worker.pem"
    key: "worker-key.pem"
  
kubeconfig_location: '/etc/kubeconfig-worker.yaml'

k8s:
  binary_dir: /usr/local/bin
  components:
  - kubectl
  - kube-proxy
  - kubelet
  additional_components:
  - https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.15.0/crictl-v1.15.0-linux-amd64.tar.gz
  - https://github.com/containernetworking/plugins/releases/download/v0.8.2/cni-plugins-linux-amd64-v0.8.2.tgz

pod_cidr: '172.31.255.0/24'
kubelet_config: /etc/kubelet-config.yaml
kubeproxy_config: /etc/kube-proxy-config.yaml
directories:
- /etc/cni/net.d