apiVersion: v1
kind: Config
current-context: default
preferences: {}
clusters:
- cluster:
    certificate-authority-data: {{ ca_authority }}
    server: https://{{ api_server }}:6443
  name: {{ cluster_name }}
contexts:
- context:
    cluster: {{ cluster_name }}
    user: {{ user }}
  name: default
users:
- name: {{ user }}
  user:
    client-certificate-data: {{ client_cert }}
    client-key-data: {{ client_key }}