---
- name: "Prepare | Certificates | Root CA"
  ca:
    cert_file: "{{ ca.cert }}"
    key_file: "{{ ca.key }}"
    config:
      C: nl
      CN: kube
  delegate_to: localhost
  register: ca_pair
  run_once: yes


- name: "Prepare | Certifiates | Ensure cert directory exists"
  file:
    path: "{{ cert.dir }}"
    state: directory
  become: yes


- name: "Prepare | Certificates | Copy Root CA key"
  copy:
    src: "{{ ca.key }}"
    dest: "{{ ca_dir }}/{{ ca.key }}"
  become: yes


- name: "Prepare | Certificates | Copy Root CA cert"
  copy:
    src: "{{ ca.cert }}"
    dest: "{{ ca_dir }}/{{ ca.cert }}"
  become: yes