---
additional_repos:
- name: docker
  description: Docker CE Stable
  url: https://download.docker.com/linux/centos/7/$basearch/stable
  gpgkey: https://download.docker.com/linux/centos/gpg

packages:
- yum-utils
- device-mapper-persistent-data
- lvm2
- containerd.io

cert:
  dir: "/etc/certificates"
  admin:
    crt: "admin.pem"
    key: "admin-key.pem"
