---
- name: 'Master | Control plane | Binaries'
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/{{ item }}"
    dest: "{{ k8s.binary_dir }}/{{ item }}"
    mode: 0777
  become: yes
  loop: '{{ k8s.components }}'

- name: 'Master | Control plane | Kube-apiserver systemd file'
  template:
    src: 'kube_apiserver.service'
    dest: '/etc/systemd/system/kube-apiserver.service'
  become: yes
  vars:
    etcd_servers: '{{ groups["master"] | etcd_cluster }}'
  notify:
  - 'Master | Reload systemd daemons'

- name: 'Master | Control plane | Kube-controller-manager systemd file'
  template:
    src: 'kube_controller_manager.service'
    dest: '/etc/systemd/system/kube-controller-manager.service'
  become: yes
  notify:
  - 'Master | Reload systemd daemons'

- name: 'Master | Control plane | Kubernetes Scheduler configuration'
  template:
    src: 'kube_scheduler.yaml'
    dest: '{{ k8s.scheduler_config_location }}'
  become: yes

- name: 'Master | Control plane | Kube-scheduler systemd file'
  template:
    src: 'kube_scheduler.service'
    dest: '/etc/systemd/system/kube-scheduler.service'
  become: yes
  notify:
  - 'Master | Reload systemd daemons'

- name: 'Master | Control plane | Systemd daemons'
  meta: flush_handlers

- name: 'Master | Control plane | Systemd services runs'
  systemd:
    name: "{{ item }}"
    state: restarted # TODO: notify
    enabled: yes
  become: yes
  loop:
  - kube-apiserver
  - kube-scheduler
  - kube-controller-manager

- name: 'Master | Control plane | Cluster Role for Kubelet Authorization'
  run_once: yes
  k8s:
    state: present
    kubeconfig: '{{ kubeconfig_location.admin }}'
    definition:
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRole
      metadata:
        annotations:
          rbac.authorization.kubernetes.io/autoupdate: "true"
        labels:
          kubernetes.io/bootstrapping: rbac-defaults
        name: system:kube-apiserver-to-kubelet
      rules:
        - apiGroups:
            - ""
          resources:
            - nodes/proxy
            - nodes/stats
            - nodes/log
            - nodes/spec
            - nodes/metrics
          verbs:
            - "*"

- name: 'Master | Control plane | Role Binding for Kubelet Authorization'
  run_once: yes
  k8s:
    state: present
    kubeconfig: '{{ kubeconfig_location.admin }}'
    definition:
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRoleBinding
      metadata:
        name: system:kube-apiserver
        namespace: ""
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:kube-apiserver-to-kubelet
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: kubernetes