---
cert:
  dir: "/etc/certificates"
  controller:
    cert: 'kube-controller-manager.pem'
    key: 'kube-controller-manager-key.pem'
  proxy:
    cert: 'proxy.pem'
    key: 'proxy-key.pem'
  scheduler:
    cert: 'kube-scheduler.pem'
    key: 'kube-scheduler-key.pem'
  kubernetes_api:
    cert: 'kubernetes.pem'
    key: 'kubernetes-key.pem'
  service_accounts:
    cert: 'service-account.pem'
    key: 'service-account-key.pem'
  admin:
    cert: "admin.pem"
    key: "admin-key.pem"

kubeconfig_location:
  proxy: '/etc/kubeconfig-proxy.yaml'
  controller: '/etc/kubeconfig-controller.yaml'
  scheduler: '/etc/kubeconfig-scheduler.yaml'
  admin: '/etc/kubeconfig-admin.yaml'

kubernetes_hostnames:
- kubernetes
- kubernetes.default
- kubernetes.default.svc
- kubernetes.default.svc.cluster
- kubernetes.svc.cluster.local

vrrp:
  config_location: '/etc/keepalived/keepalived.conf'

encryption_config:
  location: '/etc/encryption_config.yaml'

etcd_verion: 'v3.4.7'
etcd:
  dir: '/opt/etcd'
  dist_dir: '/opt/etcd/etcd-{{ etcd_verion }}-linux-amd64'
  lib_dir: '/opt/etcd/lib'
  bin_dir: '/opt/etcd/bin'
  url: 'https://github.com/etcd-io/etcd/releases/download/{{ etcd_verion }}/etcd-{{ etcd_verion }}-linux-amd64.tar.gz'
  binary: '/usr/bin/etcd'
  ctl_binary: '/usr/bin/etcdctl'
